import "./Background.css";

/*
BACKGROUND COMPONENT
This component renders an SVG background generated by haikei with various shapes.
It is used as a component rather than an image to allow for better styling and responsiveness.
*/
function Background() {
  return (
    <svg
      id="visual"
      viewBox="0 0 900 600"
      preserveAspectRatio="xMidYMid slice"
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      version="1.1"
    >
      <rect x="0" y="0" width="900" height="600" fill="#001829"></rect>
      <g fill="#ffffff">
        <path
          d="M0 -13.2L3 -4.1L12.6 -4.1L4.8 1.6L7.8 10.7L0 5L-7.8 10.7L-4.8 1.6L-12.6 -4.1L-3 -4.1Z"
          transform="translate(255 561)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(756 336)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(138 136)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(43 408)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(591 542)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(551 282)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(838 317)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(285 85)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(49 102)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(783 377)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(26 157)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(735 599)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(71 82)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(783 215)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(426 141)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(116 177)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(199 381)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(172 579)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(330 173)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(455 479)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(634 452)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(279 112)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(330 596)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(707 110)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(388 281)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(231 329)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(110 599)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(208 42)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(709 593)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(130 25)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(564 142)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(463 436)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(875 456)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(237 28)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(506 550)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(419 325)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(172 407)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(860 62)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(777 487)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(888 282)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(74 2)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(779 580)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(738 553)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(817 373)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(177 318)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(874 180)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(704 472)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(294 167)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(189 257)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(202 350)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(822 122)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(290 559)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(604 315)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(359 568)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(886 530)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(37 499)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(782 131)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(39 547)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(56 583)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(619 227)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(270 369)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(184 73)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(66 494)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(748 448)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(701 233)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(40 251)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(448 282)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(205 192)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(343 45)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(358 507)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(531 410)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(352 218)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(204 6)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(129 276)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(765 29)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(477 520)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(876 569)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(858 137)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(478 365)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(388 33)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(556 36)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(312 507)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(670 116)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(820 428)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(840 29)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(172 524)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(405 525)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(566 235)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(330 553)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(747 164)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(250 478)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(3 542)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(206 113)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(601 577)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(800 525)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(41 196)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(770 103)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(346 430)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(354 103)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(608 343)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(445 249)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(645 46)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(850 279)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(486 55)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(436 169)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(848 231)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(386 120)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(340 404)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(272 306)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(709 207)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(817 498)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(366 410)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(284 512)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(497 501)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(693 406)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(157 166)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(445 8)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(864 400)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(502 224)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(398 379)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(848 488)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(692 22)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(520 45)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(878 223)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(83 149)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(640 491)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(398 583)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(479 324)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(818 293)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(209 158)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(799 250)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(351 267)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(815 472)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(732 252)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(378 536)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(401 1)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(522 3)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(427 38)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(151 479)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(110 105)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(527 497)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(504 430)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(892 357)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(381 317)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(173 3)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(517 94)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(725 500)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(518 175)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(351 471)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(721 440)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(26 72)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(646 427)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(762 244)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(446 360)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(649 228)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(69 424)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(867 111)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(618 94)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(626 294)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(573 362)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(8 372)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(708 374)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(737 303)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(188 446)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(667 69)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(61 35)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(157 368)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(328 100)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(225 278)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(524 465)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(279 439)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(530 590)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(647 337)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(812 327)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(552 449)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(388 197)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(288 348)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(172 346)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(730 124)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(581 492)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(398 83)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(676 176)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(251 222)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(354 133)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(21 227)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(401 478)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(623 181)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(392 415)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(681 558)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(582 292)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(255 525)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(211 308)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(17 314)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(696 154)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(430 540)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(30 593)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(804 175)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(426 93)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(267 38)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(53 455)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(830 525)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(255 157)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(627 549)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(836 193)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(100 324)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(488 289)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(20 38)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(569 559)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(529 376)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(335 369)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(232 391)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(88 208)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(651 200)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(760 273)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(6 407)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(884 52)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(701 57)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(93 464)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(265 246)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(799 54)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(225 456)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(506 314)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(316 6)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(7 192)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(141 224)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(391 228)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(611 384)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(495 251)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(722 339)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(480 20)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(117 410)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(203 553)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(9 131)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(678 337)"
        ></path>
        <path
          d="M0 -5.7L1.3 -1.7L5.4 -1.7L2.1 0.7L3.3 4.6L0 2.2L-3.3 4.6L-2.1 0.7L-5.4 -1.7L-1.3 -1.7Z"
          transform="translate(36 356)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(665 286)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(456 129)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(642 110)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(546 202)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(53 315)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(848 359)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(444 566)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(745 524)"
        ></path>
        <path
          d="M0 -10.4L2.3 -3.2L9.9 -3.2L3.8 1.2L6.1 8.4L0 4L-6.1 8.4L-3.8 1.2L-9.9 -3.2L-2.3 -3.2Z"
          transform="translate(839 449)"
        ></path>
        <path
          d="M0 -11.3L2.5 -3.5L10.8 -3.5L4.1 1.3L6.7 9.2L0 4.3L-6.7 9.2L-4.1 1.3L-10.8 -3.5L-2.5 -3.5Z"
          transform="translate(230 180)"
        ></path>
        <path
          d="M0 -9.4L2.1 -2.9L9 -2.9L3.4 1.1L5.5 7.6L0 3.6L-5.5 7.6L-3.4 1.1L-9 -2.9L-2.1 -2.9Z"
          transform="translate(129 72)"
        ></path>
        <path
          d="M0 -7.6L1.7 -2.3L7.2 -2.3L2.7 0.9L4.4 6.1L0 2.9L-4.4 6.1L-2.7 0.9L-7.2 -2.3L-1.7 -2.3Z"
          transform="translate(368 362)"
        ></path>
        <path
          d="M0 -4.7L1.1 -1.5L4.5 -1.5L1.7 0.6L2.8 3.8L0 1.8L-2.8 3.8L-1.7 0.6L-4.5 -1.5L-1.1 -1.5Z"
          transform="translate(886 23)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(793 420)"
        ></path>
        <path
          d="M0 -8.5L1.9 -2.6L8.1 -2.6L3.1 1L5 6.9L0 3.2L-5 6.9L-3.1 1L-8.1 -2.6L-1.9 -2.6Z"
          transform="translate(720 167)"
        ></path>
        <path
          d="M0 -6.6L1.5 -2L6.3 -2L2.4 0.8L3.9 5.3L0 2.5L-3.9 5.3L-2.4 0.8L-6.3 -2L-1.5 -2Z"
          transform="translate(71 260)"
        ></path>
      </g>
    </svg>
  );
}

export default Background;
